remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Envys site]
description: [this is a site i made as a hobby dont expect much from it]
